From: Preston Timmons <prestontimmons@gfa.org>
Origin: https://github.com/django/django/pull/2601/
Last-Updated: 2014-06-22
Subject: Fixed #22486: Reverse raises AttributeError on partial functions.

Create the lookup_str from the original function whenever a partial
is provided as an argument to a url pattern.
---
 django/core/urlresolvers.py        |  4 ++++
 tests/urlpatterns_reverse/urls.py  |  6 +++++-
 tests/urlpatterns_reverse/views.py | 10 ++++++++++
 3 files changed, 19 insertions(+), 1 deletion(-)

--- a/django/core/urlresolvers.py
+++ b/django/core/urlresolvers.py
@@ -13,6 +13,8 @@
 import re
 from threading import local
 
+import functools
+
 from django.http import Http404
 from django.core.exceptions import ImproperlyConfigured, ViewDoesNotExist
 from django.utils.datastructures import MultiValueDict
--- a/tests/urlpatterns_reverse/urls.py
+++ b/tests/urlpatterns_reverse/urls.py
@@ -48,6 +48,10 @@
     url(r'^outer-no-kwargs/(\d+)/', include('urlpatterns_reverse.included_no_kwargs_urls')),
     url('', include('urlpatterns_reverse.extra_urls')),
 
+    # Partials should be fine.
+    url(r'^partial/', empty_view_partial, name="partial"),
+    url(r'^partial_wrapped/', empty_view_wrapped, name="partial_wrapped"),
+
     # This is non-reversible, but we shouldn't blow up when parsing it.
     url(r'^(?:foo|bar)(\w+)/$', empty_view, name="disjunction"),
 
